# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milhas', '0002_auto_20170926_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocao',
            name='quantidade',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='valor_com_desconto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
