# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milhas', '0004_auto_20171107_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocao',
            name='estado',
            field=models.TextField(default='Últimas Passagens', max_length=20),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='subtitulo',
            field=models.TextField(default='subtitulo', max_length=20),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='titulo',
            field=models.TextField(max_length=20),
        ),
    ]
