# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milhas', '0005_auto_20171107_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocao',
            name='codigo',
            field=models.CharField(max_length=20),
        ),
    ]
