# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milhas', '0006_auto_20171107_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocao',
            old_name='codigo',
            new_name='code_cupom',
        ),
        migrations.RenameField(
            model_name='promocao',
            old_name='data_alteracao',
            new_name='date_alteration',
        ),
        migrations.RenameField(
            model_name='promocao',
            old_name='data_criacao',
            new_name='date_create',
        ),
        migrations.RenameField(
            model_name='promocao',
            old_name='data_promocao_fim',
            new_name='date_offer_end',
        ),
        migrations.RenameField(
            model_name='promocao',
            old_name='data_promocao_inicio',
            new_name='date_offer_start',
        ),
        migrations.RenameField(
            model_name='promocao',
            old_name='quantidade',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='promocao',
            old_name='estado',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='promocao',
            old_name='subtitulo',
            new_name='subtitle',
        ),
        migrations.RenameField(
            model_name='promocao',
            old_name='titulo',
            new_name='title',
        ),
    ]
