# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milhas', '0007_auto_20171107_1827'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Promocao',
            new_name='Cupom',
        ),
        migrations.AlterModelOptions(
            name='cupom',
            options={'verbose_name': 'Cupom', 'verbose_name_plural': 'Cupons'},
        ),
    ]
