# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milhas', '0008_auto_20171108_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cupom',
            old_name='date_offer_end',
            new_name='cupom_end_date',
        ),
        migrations.RenameField(
            model_name='cupom',
            old_name='date_offer_start',
            new_name='cupom_start_date',
        ),
    ]
