# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('milhas', '0009_auto_20171108_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupom',
            name='cupom_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
