# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milhas', '0012_cupom_max_oferta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupom',
            name='max_oferta',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='sold_out',
            field=models.BooleanField(default=1),
        ),
    ]
