# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milhas', '0014_auto_20171113_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='MsgAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='título', max_length=20, verbose_name='Título')),
            ],
        ),
    ]
