# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 17:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milhas', '0018_cupom_time_of_the_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cupom',
            name='time_of_the_day',
        ),
        migrations.AlterField(
            model_name='cupom',
            name='cupom_start_date',
            field=models.DateTimeField(choices=[(datetime.time(7, 0), '7:00 am'), (datetime.time(8, 0), '8:00 am'), (datetime.time(9, 0), '9:00 am'), (datetime.time(18, 0), '6:00 pm'), (datetime.time(19, 0), '7:00 pm'), (datetime.time(20, 0), '8:00 pm'), (datetime.time(21, 0), '9:00 pm')], null=True, verbose_name='Data Início Cupom'),
        ),
    ]
