# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milhas', '0019_auto_20171121_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupom',
            name='cupom_start_date',
            field=models.DateTimeField(null=True, verbose_name='Data Início Cupom'),
        ),
    ]
